[package]
name = 'TransitAggregator'
version = '1.0.0'

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "80d7b03c630e0066bc12e2a3ba6f3546542bbb8c" }
Aptoswap = { local = "./exchange/aptoswap" }
Liquidswap = { git = "https://github.com/pontem-network/liquidswap.git", rev = "v0.4.3" }
LiquidswapRouterV2 = { git = 'https://github.com/pontem-network/liquidswap.git', subdir = 'liquidswap_router_v2/', rev = "v0.4.3" }
AnimeSwapV1 = { local = "./exchange/animeswap" }
PancakeSwap = { git = 'https://github.com/pancakeswap/pancake-contracts-move.git', subdir = 'pancake-swap', rev = "ffb6415eef88ef87b575305b181f74a45bfff30c" }
aux = { local = "./exchange/aux"}
Cetue-AMM = { local = "./exchange/cetus"}

[addresses]
transit_aggregator = "0x76a6de079111442b4df012efcd35da77a99446bff13f4da32e305226e23d6be1"
agg_fee_address = "0x8c0c3eab0522560d8b99104775e3fed239a15b5c11668223bd1acc5c3c4b0234"